#define PJ_GETHOSTIP_DISABLE_LOCAL_RESOLUTION 1
#define PJSIP_TRANSPORT_IDLE_TIME 720
#define PJSIP_MAX_PKT_LEN 32768
#define PJSIP_TLS_KEEP_ALIVE_INTERVAL 0
#define PJ_CONFIG_IPHONE 1
#define PJSIP_HAS_TLS_TRANSPORT 1
#define PJ_HAS_SSL_SOCK 1
#define PJ_HAS_IPV6 1
#define PJSIP_TCP_TRANSPORT_DONT_CREATE_LISTENER 1
#define PJSIP_TLS_TRANSPORT_DONT_CREATE_LISTENER 1
#include <pj/config_site_sample.h>
