/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: change_notification.schema
 * Date: 2012-08-01 20:55:34
*/
#ifndef JSON_HEADER_GUARD_1343847334_0
#define JSON_HEADER_GUARD_1343847334_0

#define CHANGE_NOTIFICATION_MESSAGE                         @"Message"
#define CHANGE_NOTIFICATION_MESSAGE_COMMAND                 @"Command"
#define CHANGE_NOTIFICATION_MESSAGE_COMMAND_PATTERN         @"change-notification"
#define BULK_CHANGE_NOTIFICATION_MESSAGE_COMMAND_PATTERN    @"bulk-cn"
#define CHANGE_NOTIFICATION_MESSAGE_DATA                    @"Data"
#define CHANGE_NOTIFICATION_DATA_QLIQ_ID                    @"qliq_id"
#define CHANGE_NOTIFICATION_MESSAGE_SUBJECT                 @"Subject"
#define CHANGE_NOTIFICATION_MESSAGE_SUBJECT_PATTERN         @"text"
#define CHANGE_NOTIFICATION_MESSAGE_TYPE                    @"Type"
#define CHANGE_NOTIFICATION_MESSAGE_TYPE_PATTERN            @"a2a"

#endif
