/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: charges-request.schema
 * Date: 2011-08-26 13:55:17
*/
#ifndef JSON_HEADER_GUARD_1314359717_0
#define JSON_HEADER_GUARD_1314359717_0

#define CHARGES_REQUEST_MESSAGE @"Message"
#define CHARGES_REQUEST_MESSAGE_COMMAND @"Command"
#define CHARGES_REQUEST_MESSAGE_COMMAND_PATTERN @"pull_request"
#define CHARGES_REQUEST_MESSAGE_DATA @"Data"
#define CHARGES_REQUEST_DATA_LAST_UPDATED @"last_updated"
#define CHARGES_REQUEST_DATA_SYNC_REQUEST_USER @"sync_request_user"
#define CHARGES_REQUEST_DATA_SYNC_REQUEST_USER_SIP_URI @"sync_request_user_sip_uri"
#define CHARGES_REQUEST_DATA_TRANSACTION_ID @"transaction_id"
#define CHARGES_REQUEST_MESSAGE_SUBJECT @"Subject"
#define CHARGES_REQUEST_MESSAGE_SUBJECT_PATTERN @"charges"
#define CHARGES_REQUEST_MESSAGE_TYPE @"Type"
#define CHARGES_REQUEST_MESSAGE_TYPE_PATTERN @"a2a"

#endif
