/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: chat-message.schema
 * Date: 2011-08-09 17:08:12
*/
#ifndef JSON_HEADER_GUARD_1312902492_0
#define JSON_HEADER_GUARD_1312902492_0

#define CHAT_MESSAGE_MESSAGE @"Message"
#define CHAT_MESSAGE_MESSAGE_COMMAND @"Command"
#define CHAT_MESSAGE_MESSAGE_COMMAND_PATTERN @"im"
#define CHAT_MESSAGE_MESSAGE_DATA @"Data"
#define CHAT_MESSAGE_MESSAGE_SUBJECT @"Subject"
#define CHAT_MESSAGE_MESSAGE_SUBJECT_PATTERN @"text"
#define CHAT_MESSAGE_MESSAGE_TYPE @"Type"
#define CHAT_MESSAGE_MESSAGE_TYPE_PATTERN @"u2u"

#endif
