/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: extended-chat-message.schema
 * Date: 2012-04-18 13:30:45
*/
#ifndef JSON_HEADER_GUARD_1334748645_0
#define JSON_HEADER_GUARD_1334748645_0

#define EXTENDED_CHAT_MESSAGE_MESSAGE                       @"Message"
#define EXTENDED_CHAT_MESSAGE_MESSAGE_COMMAND               @"Command"
#define EXTENDED_CHAT_MESSAGE_MESSAGE_COMMAND_PATTERN       @"extended-im"
#define EXTENDED_CHAT_MESSAGE_MESSAGE_DATA                  @"Data"
#define EXTENDED_CHAT_MESSAGE_DATA_ATTACHMENT               @"attachment"
#define EXTENDED_CHAT_MESSAGE_DATA_ATTACHMENTS              @"attachments"
#define EXTENDED_CHAT_MESSAGE_ATTACHMENT_CHECKSUM           @"checksum"
#define EXTENDED_CHAT_MESSAGE_ATTACHMENT_ENCRYPTION_METHOD  @"encryptionMethod"
#define EXTENDED_CHAT_MESSAGE_ATTACHMENT_FILE_NAME          @"fileName"
#define EXTENDED_CHAT_MESSAGE_ATTACHMENT_KEY                @"key"
#define EXTENDED_CHAT_MESSAGE_ATTACHMENT_MIME               @"mime"
#define EXTENDED_CHAT_MESSAGE_ATTACHMENT_SIZE               @"size"
#define EXTENDED_CHAT_MESSAGE_ATTACHMENT_THUMBNAIL          @"thumbnail"
#define EXTENDED_CHAT_MESSAGE_ATTACHMENT_URL                @"url"
#define EXTENDED_CHAT_MESSAGE_DATA_CONVERSATION_SUBJECT     @"conversationSubject"
#define EXTENDED_CHAT_MESSAGE_DATA_CONVERSATION_UUID        @"conversationUuid"
#define EXTENDED_CHAT_MESSAGE_DATA_MESSAGE_ID               @"messageId"
#define EXTENDED_CHAT_MESSAGE_DATA_PRIORITY                 @"priority"
#define EXTENDED_CHAT_MESSAGE_DATA_RECIPIENT_TYPE           @"recipientType"
#define EXTENDED_CHAT_MESSAGE_DATA_REQUIRES_ACKNOWLEDGEMENT @"requiresAcknowledgement"
#define EXTENDED_CHAT_MESSAGE_DATA_TEXT                     @"text"
#define EXTENDED_CHAT_MESSAGE_DATA_TO_USER_ID               @"toUserId"
#define EXTENDED_CHAT_MESSAGE_DATA_TYPE                     @"type"
#define EXTENDED_CHAT_MESSAGE_DATA_CREATED_AT               @"createdAt"
#define EXTENDED_CHAT_MESSAGE_MESSAGE_SUBJECT               @"Subject"
#define EXTENDED_CHAT_MESSAGE_MESSAGE_SUBJECT_PATTERN       @"text"
#define EXTENDED_CHAT_MESSAGE_MESSAGE_TYPE                  @"Type"
#define EXTENDED_CHAT_MESSAGE_MESSAGE_TYPE_PATTERN          @"u2u"

#endif
