/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: get_device_status-request.schema
 * Date: 2012-08-20 14:32:04
*/
#ifndef JSON_HEADER_GUARD_1345465924_0
#define JSON_HEADER_GUARD_1345465924_0

#define GET_DEVICE_STATUS_REQUEST_MESSAGE @"Message"
#define GET_DEVICE_STATUS_REQUEST_MESSAGE_DATA @"Data"
#define GET_DEVICE_STATUS_REQUEST_DATA_DEVICE_UUID @"device_uuid"
#define GET_DEVICE_STATUS_REQUEST_DATA_PASSWORD @"password"
#define GET_DEVICE_STATUS_REQUEST_DATA_USERNAME @"username"

#endif
