/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: get_device_status-response.schema
 * Date: 2012-08-20 14:32:24
*/
#ifndef JSON_HEADER_GUARD_1345465944_0
#define JSON_HEADER_GUARD_1345465944_0

#define GET_DEVICE_STATUS_RESPONSE_MESSAGE @"Message"
#define GET_DEVICE_STATUS_RESPONSE_MESSAGE_DATA @"Data"
#define GET_DEVICE_STATUS_RESPONSE_DATA_DEVICE_UUID @"device_uuid"
#define GET_DEVICE_STATUS_RESPONSE_DATA_LOCKED @"locked"
#define GET_DEVICE_STATUS_RESPONSE_DATA_WIPE_DATA @"wipe_data"
#define GET_DEVICE_STATUS_RESPONSE_MESSAGE_ERROR @"Error"
#define GET_DEVICE_STATUS_RESPONSE_ERROR_ERROR_CODE @"error_code"
#define GET_DEVICE_STATUS_RESPONSE_ERROR_ERROR_MSG @"error_msg"

#endif
