/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: get-file-request.schema
 * Date: 2012-04-17 15:56:07
*/
#ifndef JSON_HEADER_GUARD_1334670967_0
#define JSON_HEADER_GUARD_1334670967_0

#define GET_FILE_REQUEST_MESSAGE @"Message"
#define GET_FILE_REQUEST_MESSAGE_COMMAND @"Command"
#define GET_FILE_REQUEST_MESSAGE_COMMAND_PATTERN @"get"
#define GET_FILE_REQUEST_MESSAGE_DATA @"Data"
#define GET_FILE_REQUEST_DATA_FILE_NAME @"file_name"
#define GET_FILE_REQUEST_DATA_PASSWORD @"password"
#define GET_FILE_REQUEST_DATA_USER_ID @"user_id"
#define GET_FILE_REQUEST_MESSAGE_SUBJECT @"Subject"
#define GET_FILE_REQUEST_MESSAGE_SUBJECT_PATTERN @"file"
#define GET_FILE_REQUEST_MESSAGE_TYPE @"Type"
#define GET_FILE_REQUEST_MESSAGE_TYPE_PATTERN @"client2web"

#endif
