/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: hl7-message.schema
 * Date: 2011-10-14 11:43:07
*/
#ifndef JSON_HEADER_GUARD_1318585387_0
#define JSON_HEADER_GUARD_1318585387_0

#define HL7_MESSAGE_MESSAGE @"Message"
#define HL7_MESSAGE_MESSAGE_COMMAND @"Command"
#define HL7_MESSAGE_MESSAGE_COMMAND_PATTERN @"hl7message"
#define HL7_MESSAGE_MESSAGE_DATA @"Data"
#define HL7_MESSAGE_DATA_ADMIT_DATE @"admit_date"
#define HL7_MESSAGE_DATA_ATTENDING_PHYSICIAN @"attending_physician"
#define HL7_MESSAGE_ATTENDING_PHYSICIAN_NAME @"name"
#define HL7_MESSAGE_ATTENDING_PHYSICIAN_NPI @"npi"
#define HL7_MESSAGE_DATA_DISCHARGE_DATE @"discharge_date"
#define HL7_MESSAGE_DATA_EVENT_TYPE @"event_type"
#define HL7_MESSAGE_DATA_MESSAGE_CONTROL_ID @"message_control_id"
#define HL7_MESSAGE_DATA_FACILITY_NPI @"facility_npi"
#define HL7_MESSAGE_DATA_MRN @"mrn"
#define HL7_MESSAGE_DATA_PATIENT @"patient"
#define HL7_MESSAGE_PATIENT_DATE_OF_BIRTH @"date_of_birth"
#define HL7_MESSAGE_PATIENT_EMAIL @"email"
#define HL7_MESSAGE_PATIENT_FIRST_NAME @"first_name"
#define HL7_MESSAGE_PATIENT_GENDER @"gender"
#define HL7_MESSAGE_PATIENT_INSURANCE @"insurance"
#define HL7_MESSAGE_PATIENT_LAST_NAME @"last_name"
#define HL7_MESSAGE_PATIENT_MIDDLE_NAME @"middle_name"
#define HL7_MESSAGE_PATIENT_PHONE @"phone"
#define HL7_MESSAGE_PATIENT_RACE @"race"
#define HL7_MESSAGE_DATA_PATIENT_ACCOUNT_NUMBER @"patient_account_number"
#define HL7_MESSAGE_DATA_PATIENT_CLASS @"patient_class"
#define HL7_MESSAGE_DATA_REFERRAL_PHYSICIAN @"referral_physician"
#define HL7_MESSAGE_REFERRAL_PHYSICIAN_NAME @"name"
#define HL7_MESSAGE_REFERRAL_PHYSICIAN_NPI @"npi"
#define HL7_MESSAGE_DATA_ROOM @"room"
#define HL7_MESSAGE_MESSAGE_SUBJECT @"Subject"
#define HL7_MESSAGE_MESSAGE_SUBJECT_PATTERN @"census"
#define HL7_MESSAGE_MESSAGE_TYPE @"Type"
#define HL7_MESSAGE_MESSAGE_TYPE_PATTERN @"a2a"

#endif
