/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: message.schema
 * Date: 2011-08-08 15:57:30
*/
#ifndef JSON_HEADER_GUARD_1312811850_0
#define JSON_HEADER_GUARD_1312811850_0

#define MESSAGE_MESSAGE @"Message"
#define MESSAGE_MESSAGE_COMMAND @"Command"
#define MESSAGE_MESSAGE_DATA @"Data"
#define MESSAGE_MESSAGE_SIGNATURE @"Signature"
#define MESSAGE_MESSAGE_SUBJECT @"Subject"
#define MESSAGE_MESSAGE_TYPE @"Type"

#endif
