/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: request.json
 * Date: 2012-04-13 14:59:48
*/
#ifndef JSON_HEADER_GUARD_1334321988_0
#define JSON_HEADER_GUARD_1334321988_0

#define PUT_FILE_REQUEST_MESSAGE @"Message"
#define PUT_FILE_REQUEST_MESSAGE_COMMAND @"Command"
#define PUT_FILE_REQUEST_MESSAGE_COMMAND_PATTERN @"put"
#define PUT_FILE_REQUEST_MESSAGE_DATA @"Data"
#define PUT_FILE_REQUEST_DATA_PASSWORD @"password"
#define PUT_FILE_REQUEST_DATA_RECEIVING_USER_ID @"receiving_user_id"
#define PUT_FILE_REQUEST_DATA_USER_ID @"user_id"
#define PUT_FILE_REQUEST_MESSAGE_SUBJECT @"Subject"
#define PUT_FILE_REQUEST_MESSAGE_SUBJECT_PATTERN @"file"
#define PUT_FILE_REQUEST_MESSAGE_TYPE @"Type"
#define PUT_FILE_REQUEST_MESSAGE_TYPE_PATTERN @"client2web"

#endif
