/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: chat-event-message.json
 * Date: 2012-12-26 15:10:00
*/
#ifndef JSON_HEADER_GUARD_1356531000_0
#define JSON_HEADER_GUARD_1356531000_0

#define CHAT_EVENT_MESSAGE_ADDED @"added"
#define CHAT_EVENT_MESSAGE_EVENT_TYPE @"eventType"
#define CHAT_EVENT_MESSAGE_ORIGINATOR_QLIQ_ID @"originatorQliqId"
#define CHAT_EVENT_MESSAGE_REMOVED @"removed"
//next two keys used to modifying existing conversation on receiver side
#define CHAT_EVENT_MESSAGE_RECIPIENT_QLIQ_ID_BEFORE @"recipient_qliq_id_before" //multiparty_qliq_id or sender qliq_id before edit
#define CHAT_EVENT_MESSAGE_RECIPIENT_QLIQ_ID_AFTER @"recipient_qliq_id_after" //multiparty_qliq_id or sender qliq_id before edit
#endif
