/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: chat-message.json
 * Date: 2012-10-19 12:05:58
*/
#ifndef JSON_HEADER_GUARD_1350641158_0
#define JSON_HEADER_GUARD_1350641158_0

#define CHAT_MESSAGE_ACK_RECEIVED_AT @"ackReceivedAt"
#define CHAT_MESSAGE_ACK_SENT_AT @"ackSentAt"
#define CHAT_MESSAGE_ATTACHMENTS @"attachments"
#define CHAT_MESSAGE_ATTACHMENTS_CHECKSUM @"checksum"
#define CHAT_MESSAGE_ATTACHMENTS_ENCRYPTION_METHOD @"encryptionMethod"
#define CHAT_MESSAGE_ATTACHMENTS_FILE_NAME @"fileName"
#define CHAT_MESSAGE_ATTACHMENTS_KEY @"key"
#define CHAT_MESSAGE_ATTACHMENTS_MIME @"mime"
#define CHAT_MESSAGE_ATTACHMENTS_SIZE @"size"
#define CHAT_MESSAGE_ATTACHMENTS_THUMBNAIL @"thumbnail"
#define CHAT_MESSAGE_ATTACHMENTS_URL @"url"
#define CHAT_MESSAGE_CREATED_AT @"createdAt"
#define CHAT_MESSAGE_DELIVERY_STATUS @"deliveryStatus"
#define CHAT_MESSAGE_FAILED_ATTEMPTS @"failedAttempts"
#define CHAT_MESSAGE_FROM_USER_ID @"fromUserId"
#define CHAT_MESSAGE_FROM_USER_NAME @"fromUserName"
#define CHAT_MESSAGE_LAST_SENT_AT @"lastSentAt"
#define CHAT_MESSAGE_PRIORITY @"priority"
#define CHAT_MESSAGE_READ_AT @"readAt"
#define CHAT_MESSAGE_RECALLED @"recalled"
#define CHAT_MESSAGE_RECEIVED_AT @"receivedAt"
#define CHAT_MESSAGE_RECEIVED_ON_DEVICE @"receivedOnDevice"
#define CHAT_MESSAGE_REQUIRES_ACK @"requiresAck"
#define CHAT_MESSAGE_SENT_FROM_DEVICE @"sentFromDevice"
#define CHAT_MESSAGE_STATUS_LOG @"statusLog"
#define CHAT_MESSAGE_STATUS_LOG_STATUS @"status"
#define CHAT_MESSAGE_STATUS_LOG_TIME @"time"
#define CHAT_MESSAGE_SUBJECT @"subject"
#define CHAT_MESSAGE_TEXT @"text"
#define CHAT_MESSAGE_TO_USER_ID @"toUserId"
#define CHAT_MESSAGE_TO_USER_NAME @"toUserName"
#define CHAT_MESSAGE_UUID @"uuid"
#define CHAT_MESSAGE_METADATA @"metadata"
#define CHAT_MESSAGE_CONVERSATION_UUID @"conversationUuid"
#endif
