/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: facility.json
 * Date: 2011-11-22 14:57:28
*/
#ifndef JSON_HEADER_GUARD_1321970248_0
#define JSON_HEADER_GUARD_1321970248_0

#define FACILITY_ADDRESS @"address"
#define FACILITY_CITY @"city"
#define FACILITY_NAME @"name"
#define FACILITY_NPI @"npi"
#define FACILITY_PHONE @"phone"
#define FACILITY_SPECIALTY @"specialty"
#define FACILITY_STATE @"state"
#define FACILITY_ZIP @"zip"

#endif
