/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: metadata.json
 * Date: 2011-11-22 14:58:11
*/
#ifndef JSON_HEADER_GUARD_1321970291_0
#define JSON_HEADER_GUARD_1321970291_0

#define METADATA_AUTHOR @"author"
#define METADATA_REV @"rev"
#define METADATA_SEQ @"seq"
#define METADATA_UUID @"uuid"
#define METADATA_VERSION @"version"

#endif
