/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: nurse.json
 * Date: 2012-01-16 16:31:57
*/
#ifndef JSON_HEADER_GUARD_1326727917_0
#define JSON_HEADER_GUARD_1326727917_0

#define NURSE_EMAIL @"email"
#define NURSE_FACILITY_NPI @"facilityNpi"
#define NURSE_NAME @"name"
#define NURSE_NPI @"npi"
#define NURSE_PHONE @"phone"
#define NURSE_SPECIALTY @"specialty"

#endif
