/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: patient.json
 * Date: 2011-11-22 14:56:29
*/
#ifndef JSON_HEADER_GUARD_1321970189_0
#define JSON_HEADER_GUARD_1321970189_0

#define PATIENT_DOB @"dob"
#define PATIENT_EMAIL @"email"
#define PATIENT_FIRST_NAME @"firstName"
#define PATIENT_GENDER @"gender"
#define PATIENT_INSURANCE @"insurance"
#define PATIENT_LAST_NAME @"lastName"
#define PATIENT_MIDDLE_NAME @"middleName"
#define PATIENT_PHONE @"phone"
#define PATIENT_RACE @"race"

#endif
