/*
 * This file was automatically generated by JSON Schema Editor
 * Schema: physician.json
 * Date: 2011-11-22 14:57:53
*/
#ifndef JSON_HEADER_GUARD_1321970273_0
#define JSON_HEADER_GUARD_1321970273_0

#define PHYSICIAN_ADDRESS @"address"
#define PHYSICIAN_CITY @"city"
#define PHYSICIAN_EMAIL @"email"
#define PHYSICIAN_FAX @"fax"
#define PHYSICIAN_MOBILE @"mobile"
#define PHYSICIAN_NAME @"name"
#define PHYSICIAN_NPI @"npi"
#define PHYSICIAN_PHONE @"phone"
#define PHYSICIAN_SPECIALTY @"specialty"
#define PHYSICIAN_STATE @"state"
#define PHYSICIAN_ZIP @"zip"

#endif
